// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjnWMsYJfE16cCWHBeRLFMVEBwR4JdseY',
    appId: '1:431432157041:web:854a92474cf43bbe9598d0',
    messagingSenderId: '431432157041',
    projectId: 'app-aposento-alto-calle80',
    authDomain: 'app-aposento-alto-calle80.firebaseapp.com',
    storageBucket: 'app-aposento-alto-calle80.appspot.com',
    measurementId: 'G-VTB8Y2KGFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8N3AYJ_Kd3pU8Bsc1lGd5Mdex7IZUeUE',
    appId: '1:431432157041:android:89ba87029dad029b9598d0',
    messagingSenderId: '431432157041',
    projectId: 'app-aposento-alto-calle80',
    storageBucket: 'app-aposento-alto-calle80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ebjuBS_ZwhTnkgX_5TXoYrYSNbNuUhg',
    appId: '1:431432157041:ios:dd44d157c3f776379598d0',
    messagingSenderId: '431432157041',
    projectId: 'app-aposento-alto-calle80',
    storageBucket: 'app-aposento-alto-calle80.appspot.com',
    androidClientId: '431432157041-kie46cc0kqmg8p6jo7t1jer4b8qmt4iq.apps.googleusercontent.com',
    iosClientId: '431432157041-uee57rt27eopt9hs468a5gm9hnppsu99.apps.googleusercontent.com',
    iosBundleId: 'com.example.appAposentoAltoCalle80',
  );
}
